;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-scroll-up
        haskell-indentation-common-electric-command
        mark-sexp
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        haskell-process-load-file
        smex
        ))
