(deftheme brutalist-dark
  "Created 2020-05-28.")

(custom-theme-set-faces
 'brutalist-dark
 '(button ((t (:foreground "#eeeee8" :underline t))))
 '(cursor ((t (:background "#eeeee8" :foreground "white smoke"))))
 '(custom-variable-tag ((t (:foreground "#eeeee8" :weight bold))))
 '(italic ((t (:slant italic))))
 '(error ((t (:inherit fixed-pitch :foreground "#eeeee8" :weight bold))))
 '(font-lock-builtin-face ((t (:inherit fixed-pitch :foreground "#eeeee8"))))
 '(font-lock-comment-face ((t (:inherit fixed-pitch :foreground "gray70"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-constant-face ((t (:inherit fixed-pitch :foreground "#eeeee8"))))
 '(font-lock-doc-face ((t (:inherit fixed-pitch :foreground "gray70" :slant italic))))
 '(font-lock-function-name-face ((t (::inherit fixed-pitch foreground "#eeeee8"))))
 '(font-lock-keyword-face ((t (:inherit fixed-pitch :foreground "#eeeee8" :weight bold))))
 '(font-lock-preprocessor-face ((t (:inherit fixed-pitch :foreground "#eeeee8" :slant italic))))
 '(font-lock-string-face ((t (:inherit fixed-pitch :foreground "light blue"))))
 '(font-lock-type-face ((t (:inherit fixed-pitch :foreground "#eeeee8" :underline t))))
 '(font-lock-variable-name-face ((t (:inherit fixed-pitch :foreground "#eeeee8" :underline nil))))
 '(font-lock-warning-face ((t (:inherit error))))
 '(fringe ((t (:background "gray20" :foreground "#eeeee8"))))
 '(highlight ((t nil)))
 '(lazy-highlight ((t (:background "DarkGreen" :slant italic))))
 '(hl-line ((t (:background "gray12"))))
 '(ido-first-match ((t (:foreground "#eeeee8"))))
 '(ido-only-match ((t (:foreground "#eeeee8"))))
 '(ido-subdir ((t (:foreground "#eeeee8"))))
 '(isearch ((t (:background "sea green" :foreground "#eeeee8"))))
 '(link ((t (:foreground "light blue" :underline t :inherit fixed-pitch))))
 '(minibuffer-prompt ((t (:inherit fixed-pitch :foreground "#eeeee8" :weight bold))))
 '(mode-line ((t (:inherit fixed-pitch :background "#888888" :foreground "#eeeee8" :height 0.8))))
 '(mode-line-inactive ((t (:background "#888888" :foreground "#888888" :height 0.8))))
 '(region ((t (:background "grey40" :foreground "#eeeee8" :inverse-video nil))))
 '(slime-repl-inputed-output-face ((t (:foreground "#eeeee8"))))
 '(whitespace-line ((t (:background "LightCyan" :foreground "#eeeee8"))))
 '(diff-added ((t (:background "#334433"))))
 '(diff-removed ((t (:background "#443333"))))
 '(diff-refine-added ((t (:background "#336633"))))
 '(diff-refine-removed ((t (:background "#883333"))))
 '(compilation-error ((t (:inherit error))))
 '(flycheck-error ((t (:inherit error))))
 '(flycheck-warning ((t (:inherit warning))))
 '(dired-directory ((t (:weight bold))))
 '(company-echo-common ((t (:foreground "#eeeee8"))))
 '(company-tooltip-selection ((t (:background "grey40"))))
 '(sp-show-pair-match-face ((t (:foreground "#aaccff" :weight bold))))
 '(sp-show-pair-mismatch-face ((t (:background "red" :foreground "#aaccff" :weight bold))))
 '(show-paren-match ((t (:foreground "#aaccff" :weight bold))))
 '(show-paren-mismatch ((t (:background "red" :foreground "#aaccff" :weight bold))))
 '(default ((t (:background "gray6" :foreground "#eeeee8")))))

(provide-theme 'brutalist-dark)
