(deftheme ultralisk
  "Created 2020-05-29.")

(custom-theme-set-variables
 'ultralisk
 '(fringe-mode 4)
 '(ansi-color-names-vector ["#110F13" "#B13120" "#719F34" "#CEAE3E" "#7C9FC9" "#7868B5" "#009090" "#F4EAD5"]))

(custom-theme-set-faces
 'ultralisk
 '(default ((t (:background "#0d090f" :foreground "#F4EAD5"))))
 '(cursor ((((class color) (min-colors 257)) (:background "#fc20bb")) (((class color) (min-colors 256)) (:background "#fc20bb")) (((class color) (min-colors 16)) (:background "red"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#B13120" :background "#1D1B25"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#fc20bb")) (((class color) (min-colors 256)) (:foreground "#fc20bb")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(highlight ((((class color) (min-colors 257)) (:background "#fc20bb" :foreground "#1b1d1e" :distant-foreground "#DFDFDF")) (((class color) (min-colors 256)) (:background "#fc20bb" :foreground "#1b1d1e" :distant-foreground "#dfdfdf")) (((class color) (min-colors 16)) (:background "red" :foreground "black" :distant-foreground "white"))))
 '(region ((((class color) (min-colors 257)) (:background "#464849" :foreground nil :distant-foreground "#b0b0b0" :extend t)) (((class color) (min-colors 256)) (:background "#6a6c6c" :foreground nil :distant-foreground "#b0b0b0" :extend t)) (((class color) (min-colors 16)) (:background "black" :foreground nil :distant-foreground "white" :extend t))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#505050")) (((class color) (min-colors 256)) (:foreground "#505050")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#505050" :extend t)) (((class color) (min-colors 256)) (:background "#505050" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :extend t))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#d02b61")) (((class color) (min-colors 256)) (:background "#d02b61")) (((class color) (min-colors 16)) (:background "red"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#b77fdb")) (((class color) (min-colors 256)) (:foreground "#b77fdb")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#808080" :background nil :slant italic)) (((class color) (min-colors 256)) (:foreground "#808080" :background nil :slant italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :background nil :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :foreground "#9f9f9f" :slant normal)) (((class color) (min-colors 256)) (:inherit font-lock-comment-face :foreground "#9f9f9f" :slant normal)) (((class color) (min-colors 16)) (:inherit font-lock-comment-face :foreground "brightblack" :slant normal))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#b77fdb" :weight bold)) (((class color) (min-colors 256)) (:foreground "#b77fdb" :weight bold)) (((class color) (min-colors 16)) (:foreground "magenta" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#6c9ef8")) (((class color) (min-colors 256)) (:foreground "#6c9ef8")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 256)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 256)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 256)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 256)) (:inherit bold :foreground "#6c9ef8")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#d08928")) (((class color) (min-colors 256)) (:foreground "#d08928")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#00aa80")) (((class color) (min-colors 256)) (:foreground "#00aa80")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#5699AF")) (((class color) (min-colors 256)) (:foreground "#5699AF")) (((class color) (min-colors 16)) (:foreground "cyan"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#eeeee8"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#fc20bb" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground "#fc20bb" :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#009090" :background "#172028"))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#505050")) (((class color) (min-colors 256)) (:inherit default :foreground "#505050")) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack"))))
 '(header-line ((((class color) (min-colors 257)) (:inherit mode-line :distant-foreground "#1b1d1e")) (((class color) (min-colors 256)) (:inherit mode-line :distant-foreground "#1b1d1e")) (((class color) (min-colors 16)) (:inherit mode-line :distant-foreground nil))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#1b1d1e" :foreground "#dddddd")) (((class color) (min-colors 256)) (:background "#1b1d1e" :foreground "#dddddd")) (((class color) (min-colors 16)) (:background nil :foreground "white"))))
 '(mode-line ((((class color) (min-colors 257)) (:background "#202222" :foreground nil :box nil)) (((class color) (min-colors 256)) (:background "#1b1d1e" :foreground nil :box nil)) (((class color) (min-colors 16)) (:background "black" :foreground nil :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((((class color) (min-colors 257)) (:foreground "#fc20bb")) (((class color) (min-colors 256)) (:foreground "#fc20bb")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(mode-line-highlight ((((class color) (min-colors 257)) (:inherit highlight :distant-foreground "#1b1d1e")) (((class color) (min-colors 256)) (:inherit highlight :distant-foreground "#1b1d1e")) (((class color) (min-colors 16)) (:inherit highlight :distant-foreground nil))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:background "#222424" :foreground "#505050" :box nil)) (((class color) (min-colors 256)) (:background "#262829" :foreground "#505050" :box nil)) (((class color) (min-colors 16)) (:background nil :foreground "brightblack" :box nil))))
 '(isearch ((t (:inherit lazy-highlight :weight bold))))
 '(isearch-fail ((((class color) (min-colors 257)) (:background "#d02b61" :foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 256)) (:background "#d02b61" :foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground "black" :weight bold))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:background "#20bbfc" :foreground "#1b1d1e" :distant-foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 256)) (:background "#20bbfc" :foreground "#1b1d1e" :distant-foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 16)) (:background "cyan" :foreground nil :distant-foreground "black" :weight bold))))
 '(match ((((class color) (min-colors 257)) (:foreground "#60aa00" :background "#1b1d1e" :weight bold)) (((class color) (min-colors 256)) (:foreground "#60aa00" :background "#1b1d1e" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :background "black" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(bold ((((class color) (min-colors 257)) (:weight bold :foreground nil)) (((class color) (min-colors 256)) (:weight bold :foreground nil)) (((class color) (min-colors 16)) (:weight bold :foreground nil))))
 '(italic ((t (:slant italic))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(nobreak-space ((t (:inherit default :underline nil))))
 '(vertical-border ((((class color) (min-colors 257)) (:background "#303030" :foreground "#303030")) (((class color) (min-colors 256)) (:background "#303030" :foreground "#303030")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightblack"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#d02b61")) (((class color) (min-colors 256)) (:foreground "#d02b61")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#d08928")) (((class color) (min-colors 256)) (:foreground "#d08928")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(line-number ((((class color) (min-colors 257)) (:inherit default :foreground "#505050" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 256)) (:inherit default :foreground "#505050" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit (hl-line default) :foreground "#20bbfc" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil :background "#1b1d1e")) (((class color) (min-colors 256)) (:inherit (hl-line default) :foreground "#20bbfc" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil :background "#1b1d1e")) (((class color) (min-colors 16)) (:inherit (hl-line default) :foreground "cyan" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil :background nil))))
 '(compilation-column-number ((t (:inherit font-lock-comment-face))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#fc20bb")) (((class color) (min-colors 256)) (:foreground "#fc20bb")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(compilation-error ((t (:inherit error :weight bold))))
 '(compilation-warning ((t (:inherit warning :slant italic))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error))))
 '(custom-button ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :background "#1b1d1e" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :background "#1b1d1e" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-unraised ((((class color) (min-colors 257)) (:foreground "#a9a1e1" :background "#1b1d1e" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#a9a1e1" :background "#1b1d1e" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightmagenta" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 257)) (:foreground "#1b1d1e" :background "#a9a1e1" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#1b1d1e" :background "#a9a1e1" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightmagenta" :box (:line-width 1 :style none)))))
 '(custom-button-pressed ((((class color) (min-colors 257)) (:foreground "#1b1d1e" :background "#6c9ef8" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#1b1d1e" :background "#6c9ef8" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-button-mouse ((((class color) (min-colors 257)) (:foreground "#1b1d1e" :background "#6c9ef8" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#1b1d1e" :background "#6c9ef8" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-variable-button ((((class color) (min-colors 257)) (:foreground "#60aa00" :underline t)) (((class color) (min-colors 256)) (:foreground "#60aa00" :underline t)) (((class color) (min-colors 16)) (:foreground "green" :underline t))))
 '(custom-saved ((((class color) (min-colors 257)) (:foreground "#60aa00" :background "#283918" :bold t)) (((class color) (min-colors 256)) (:foreground "#60aa00" :background "#283918" :bold t)) (((class color) (min-colors 16)) (:foreground "green" :background nil :bold t))))
 '(custom-comment ((((class color) (min-colors 257)) (:foreground "#dddddd" :background "#464849")) (((class color) (min-colors 256)) (:foreground "#dddddd" :background "#6a6c6c")) (((class color) (min-colors 16)) (:foreground "white" :background "black"))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#505050")) (((class color) (min-colors 256)) (:foreground "#505050")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(custom-modified ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :background "#2b3649")) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :background "#2b3649")) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:foreground "#b77fdb")) (((class color) (min-colors 256)) (:foreground "#b77fdb")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(custom-visibility ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :underline nil)) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :underline nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline nil))))
 '(custom-group-subtitle ((((class color) (min-colors 257)) (:foreground "#d02b61")) (((class color) (min-colors 256)) (:foreground "#d02b61")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:foreground "#6c9ef8")) (((class color) (min-colors 256)) (:foreground "#6c9ef8")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(custom-set ((((class color) (min-colors 257)) (:foreground "#d08928" :background "#1b1d1e")) (((class color) (min-colors 256)) (:foreground "#d08928" :background "#1b1d1e")) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-themed ((((class color) (min-colors 257)) (:foreground "#d08928" :background "#1b1d1e")) (((class color) (min-colors 256)) (:foreground "#d08928" :background "#1b1d1e")) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-invalid ((((class color) (min-colors 257)) (:foreground "#d02b61" :background "#3f1f2b")) (((class color) (min-colors 256)) (:foreground "#d02b61" :background "#3f1f2b")) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#60aa00" :background "#283918")) (((class color) (min-colors 256)) (:foreground "#60aa00" :background "#283918")) (((class color) (min-colors 16)) (:foreground "green" :background nil))))
 '(custom-changed ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :background "#1b1d1e")) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :background "#1b1d1e")) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#b77fdb")) (((class color) (min-colors 256)) (:foreground "#b77fdb")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(dired-ignored ((((class color) (min-colors 257)) (:foreground "#808080")) (((class color) (min-colors 256)) (:foreground "#808080")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#d02b61")) (((class color) (min-colors 256)) (:foreground "#d02b61")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :weight bold)) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#da8548" :weight bold)) (((class color) (min-colors 256)) (:foreground "#dd8844" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#b77fdb" :weight bold :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#b77fdb" :weight bold :inverse-video t)) (((class color) (min-colors 16)) (:foreground "magenta" :weight bold :inverse-video t))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#dddddd" :underline t)) (((class color) (min-colors 256)) (:foreground "#dddddd" :underline t)) (((class color) (min-colors 16)) (:foreground "white" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#00aa80" :weight bold)) (((class color) (min-colors 256)) (:foreground "#00aa80" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightcyan" :weight bold))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#d08928")) (((class color) (min-colors 256)) (:foreground "#d08928")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 257)) (:background "#222425" :weight bold :extend t)) (((class color) (min-colors 256)) (:background "#222425" :weight bold :extend t)) (((class color) (min-colors 16)) (:background nil :weight bold :extend t))))
 '(ediff-fine-diff-B ((t (:inherit ediff-fine-diff-A))))
 '(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
 '(ediff-current-diff-A ((((class color) (min-colors 257)) (:background "#1e2021" :extend t)) (((class color) (min-colors 256)) (:background "#1e2021" :extend t)) (((class color) (min-colors 16)) (:background nil :extend t))))
 '(ediff-current-diff-B ((t (:inherit ediff-current-diff-A))))
 '(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-A ((t (:inherit hl-line))))
 '(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
 '(flx-highlight-face ((((class color) (min-colors 257)) (:weight bold :foreground "#d08928" :underline nil)) (((class color) (min-colors 256)) (:weight bold :foreground "#d08928" :underline nil)) (((class color) (min-colors 16)) (:weight bold :foreground "yellow" :underline nil))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#262829" :extend t)) (((class color) (min-colors 256)) (:background "#262829" :extend t)) (((class color) (min-colors 16)) (:background nil :extend t))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(ido-indicator ((((class color) (min-colors 257)) (:foreground "#d02b61" :background "#1b1d1e")) (((class color) (min-colors 256)) (:foreground "#d02b61" :background "#1b1d1e")) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#808080")) (((class color) (min-colors 256)) (:foreground "#808080")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#fc20bb" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fc20bb" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :weight bold))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#fc20bb" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fc20bb" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 257)) (:inherit message-header-to :foreground "#d61b9e")) (((class color) (min-colors 256)) (:inherit message-header-to :foreground "#d61b9e")) (((class color) (min-colors 16)) (:inherit message-header-to :foreground "red"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#d08928")) (((class color) (min-colors 256)) (:foreground "#d08928")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#9f9f9f")) (((class color) (min-colors 256)) (:foreground "#9f9f9f")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#808080")) (((class color) (min-colors 256)) (:foreground "#808080")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#808080" :slant italic)) (((class color) (min-colors 256)) (:foreground "#808080" :slant italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :slant italic))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#b77fdb")) (((class color) (min-colors 256)) (:foreground "#b77fdb")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(widget-button-pressed ((((class color) (min-colors 257)) (:foreground "#d02b61")) (((class color) (min-colors 256)) (:foreground "#d02b61")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 257)) (:foreground "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(window-divider ((t (:inherit vertical-border))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider))))
 '(anzu-replace-highlight ((((class color) (min-colors 257)) (:background "#1b1d1e" :foreground "#d02b61" :weight bold :strike-through t)) (((class color) (min-colors 256)) (:background "#1b1d1e" :foreground "#d02b61" :weight bold :strike-through t)) (((class color) (min-colors 16)) (:background "black" :foreground "red" :weight bold :strike-through t))))
 '(anzu-replace-to ((((class color) (min-colors 257)) (:background "#1b1d1e" :foreground "#60aa00" :weight bold)) (((class color) (min-colors 256)) (:background "#1b1d1e" :foreground "#60aa00" :weight bold)) (((class color) (min-colors 16)) (:background "black" :foreground "green" :weight bold))))
 '(company-tooltip ((t (:inherit tooltip))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#fc20bb" :distant-foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fc20bb" :distant-foreground "#1b1d1e" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :distant-foreground "black" :weight bold))))
 '(company-tooltip-search ((((class color) (min-colors 257)) (:background "#fc20bb" :foreground "#1b1d1e" :distant-foreground "#dddddd" :weight bold)) (((class color) (min-colors 256)) (:background "#fc20bb" :foreground "#1b1d1e" :distant-foreground "#dddddd" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground nil :distant-foreground "white" :weight bold))))
 '(company-tooltip-search-selection ((((class color) (min-colors 257)) (:background "#1c1e1e")) (((class color) (min-colors 256)) (:background "#1c1e1e")) (((class color) (min-colors 16)) (:background nil))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#262829" :weight bold :foreground "#fc20bb")) (((class color) (min-colors 256)) (:background "#262829" :weight bold :foreground "#fc20bb")) (((class color) (min-colors 16)) (:background nil :weight bold :foreground "red"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#b77fdb" :foreground "#1b1d1e" :distant-foreground "#dddddd")) (((class color) (min-colors 256)) (:background "#b77fdb" :foreground "#1b1d1e" :distant-foreground "#dddddd")) (((class color) (min-colors 16)) (:background "magenta" :foreground nil :distant-foreground "white"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:foreground "#a9a1e1" :distant-foreground "#1b1d1e")) (((class color) (min-colors 256)) (:foreground "#a9a1e1" :distant-foreground "#1b1d1e")) (((class color) (min-colors 16)) (:foreground "brightmagenta" :distant-foreground nil))))
 '(company-scrollbar-bg ((t (:inherit tooltip))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#fc20bb")) (((class color) (min-colors 256)) (:background "#fc20bb")) (((class color) (min-colors 16)) (:background "red"))))
 '(company-preview ((((class color) (min-colors 257)) (:foreground "#808080")) (((class color) (min-colors 256)) (:foreground "#808080")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:background "#303030" :foreground "#fc20bb")) (((class color) (min-colors 256)) (:background "#303030" :foreground "#fc20bb")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "red"))))
 '(company-preview-search ((t (:inherit company-tooltip-search))))
 '(company-template-field ((t (:inherit match))))
 '(diff-hl-change ((((class color) (min-colors 257)) (:foreground "#da8548" :background "#da8548")) (((class color) (min-colors 256)) (:foreground "#dd8844" :background "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred" :background "brightred"))))
 '(diff-hl-delete ((((class color) (min-colors 257)) (:foreground "#d02b61" :background "#d02b61")) (((class color) (min-colors 256)) (:foreground "#d02b61" :background "#d02b61")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(diff-hl-insert ((((class color) (min-colors 257)) (:foreground "#60aa00" :background "#60aa00")) (((class color) (min-colors 256)) (:foreground "#60aa00" :background "#60aa00")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(diff-added ((((class color) (min-colors 257)) (:inherit hl-line :foreground "#60aa00")) (((class color) (min-colors 256)) (:inherit hl-line :foreground "#60aa00")) (((class color) (min-colors 16)) (:inherit hl-line :foreground "green"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diff-context ((((class color) (min-colors 257) (background dark)) (:foreground "#c2c2c2")) (((class color) (min-colors 256) (background dark)) (:foreground "#c2c2c2")) (((class color) (min-colors 16) (background dark)) (:foreground "white")) (((class color) (min-colors 257) (background light)) (:foreground "#e1e1e1")) (((class color) (min-colors 256) (background light)) (:foreground "#e1e1e1")) (((class color) (min-colors 16) (background light)) (:foreground "white"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#d02b61" :background "#303030")) (((class color) (min-colors 256)) (:foreground "#d02b61" :background "#303030")) (((class color) (min-colors 16)) (:foreground "red" :background "brightblack"))))
 '(diff-header ((((class color) (min-colors 257)) (:foreground "#00aa80" :background nil)) (((class color) (min-colors 256)) (:foreground "#00aa80" :background nil)) (((class color) (min-colors 16)) (:foreground "brightcyan" :background nil))))
 '(diff-file-header ((((class color) (min-colors 257)) (:foreground "#6c9ef8" :background nil)) (((class color) (min-colors 256)) (:foreground "#6c9ef8" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 257)) (:foreground "#a9a1e1")) (((class color) (min-colors 256)) (:foreground "#a9a1e1")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diff-refine-added ((t (:inherit diff-added :inverse-video t))))
 '(diff-refine-changed ((t (:inherit diff-changed :inverse-video t))))
 '(diff-refine-removed ((t (:inherit diff-removed :inverse-video t))))
 '(flycheck-error ((((class color) (min-colors 257)) (:underline (:style wave :color "#d02b61"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#d02b61"))) (((class color) (min-colors 16)) (:underline (:style wave :color "red")))))
 '(flycheck-warning ((((class color) (min-colors 257)) (:underline (:style wave :color "#d08928"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#d08928"))) (((class color) (min-colors 16)) (:underline (:style wave :color "yellow")))))
 '(flycheck-info ((((class color) (min-colors 257)) (:underline (:style wave :color "#60aa00"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#60aa00"))) (((class color) (min-colors 16)) (:underline (:style wave :color "green")))))
 '(show-paren-match ((t (:foreground "#E0E4CC" :background "#D94A05"))))
 '(show-paren-mismatch ((t (:foreground "#D94A05" :background "#251C1E"))))
 '(ido-incomplete-regexp ((t (:foreground "#B13120" :background "#1F1710"))))
 '(whitespace-empty ((t (:foreground "#CEAE3E" :background "#031316"))))
 '(whitespace-hspace ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-indentation ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-line ((t (:foreground "#D94A05" :background "#031316"))))
 '(whitespace-newline ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-space ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-space-after-tab ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-tab ((t (:foreground "#073E46" :background "#031316"))))
 '(whitespace-trailing ((t (:foreground "#B13120" :background "#031316"))))
 '(org-date ((t (:foreground "#7868B5" :background "#1D1B25"))))
 '(org-done ((t (:foreground "#719F34" :background "#1A2321"))))
 '(org-hide ((t (:foreground "#333333" :background "#0A0A0A"))))
 '(org-link ((t (:foreground "#7C9FC9" :background "#1E252F"))))
 '(org-todo ((t (:foreground "#B13120" :background "#1D1515"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#D65921"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#2B88A8"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#FFA07E"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#30D039"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#58A0A2"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#6070DF"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#D78060"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#FFDD77"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#44FF88"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#F92672")))))

(provide-theme 'ultralisk)
